steps:
# Build the image
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/api', '.' ]
# Push the image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/api:latest']
# Deploy image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'api'
  - '--image'
  - 'gcr.io/$PROJECT_ID/api:latest'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--update-env-vars'
  - 'NODE_ENV=production'
  - '--allow-unauthenticated'
images:
  - 'gcr.io/$PROJECT_ID/api'
